### PR TITLE
#66 fix & settings page additions

### LINKED ISSUE #66: Not possible to change websocket port in client
the `wsPort` parameter works as expected on my custom server, but it seems is not possible to change it on the client.

https://github.com/Code-Forge-Net/Remix-Dev-Tools/blob/50d55572cde95f6514d0f1cccb184cc01575632c/src/RemixDevTools/hooks/useDevServerConnection.ts#L52

Although the parameter _can_ be passed to `useDevServerConnection` its always called with no params, so default 8080 is used

### PR DESCRIPTION
**Pull request by AlemTuzlak**
# Description

Moved everything to settings

Fixes #66

### CODE REVIEW

File: src/dev-server/init.ts [hunk 1]
```diff
@@ -78,6 +79,9 @@ const installDevToolsGlobals = (config?: DevToolsServerConfig) => {
 
     ["SIGINT", "SIGTERM"].forEach((event) => {
       process.on(event, () => {
+        ws.clients.forEach((client) => {
+          client.close();
+        });
```
Comment (AlemTuzlak) [inline src/dev-server/init.ts:84]: @xHomu hopefully this fixes it, mind testing on v3.4.0? Will be up in a minute
